cart/urls.py
from django.urls import path
from .views import view_cart, add_to_cart, remove_cart

urlpatterns = [
    path('view/', view_cart, name="view_cart"),
    path('add/', add_to_cart, name="add_to_cart"),
    path('remove/', remove_cart, name="remove_cart")
]

products/urls.py
from django.urls import path
from .views import product_list, product_detail, filter_product_list, add_product, edit_product

urlpatterns = [
    path('', product_list, name='product_list'),
    path('filter/', filter_product_list, name='filter_product_list'),
    path('add_product/', add_product, name='add_product'),
    path('<int:id>/edit/', edit_product, name='edit_product'),
    path('<int:id>/', product_detail, name='product_detail'),
    ]

products/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from accounts.models import Seller

class Artist(models.Model):
    name = models.CharField(max_length=100)
    description = models.TextField(default="Enter Description")
    
    def __str__(self):
        return self.name


# Create your models here.
class Product(models.Model):
    FORMAAT_CHOICES = (
	    ('X', 'Kies formaat'),
        ('G', 'Groot'),
        ('M', 'Normaal'),
        ('K', 'Klein'),
    )
    
    ORIËNTATIE_CHOICES = (
	    ('X', 'Kies oriëntatie'),
        ('L', 'Liggend'),
        ('S', 'Staand'),
        ('V', 'Vierkant'),
        ('D', 'Driedimensionaal')
    )
    
    TECHNIEK_CHOICES = (
	    ('X', 'Kies techniek'),
        ('S', 'Sculptuur'),
        ('F', 'Fotografie'),
	    ('D', 'Doek, Paneel'),
        ('P', 'Papier'),
        ('G', 'Grafiek'),
        ('D', 'Digitale techniek'),
        ('O', 'Overig'),
    )

    PRIJS_CHOICES = (
    	('X', 'Kies prijs'),
    	('B', 'Tot 499 euro'),
    	('M', '500 tot 999 euro'),
    	('H', '1000 to 2999 euro'),
    	('L', '3000 euro en hoger')
    )
	
    PRIJSTYPE_CHOICES = (
    	('X', 'Kies een prijstype'),
    	('B', 'Geen voorkeur'),	
    	('K', 'Koop'),
    	('H', 'Huur'),
    )

    STIJL_CHOICES = (
    	('X', 'Kies jouw kunststijl'),
    	('R', 'Realistisch'),
    	('I', 'Impresionistisch'),
    	('G', 'Gestileerd'),
    	('A', 'Abstract'),
    	
    )
    
    THEME_CHOICES = (
        ('X', 'Kies jouw thema'),
        ('A', 'Architectuur'),
        ('D', 'Dieren'),
        ('E', 'Eten en Drinken'),
        ('L', 'Landschap en Natuur'),
        ('C', 'Cultuur en Land'),
        ('M', 'Mens en Portret'),
        ('O', 'Overig'),
    )
    
    LIJST_CHOICES = (
        ('L', 'Ja'),
        ('Z', 'Nee'),
    )
    
    seller = models.ForeignKey(Seller, blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)
    description = models.TextField(default="Enter Description")
    price = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    rent = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    lengthcm = models.DecimalField(max_digits=6, decimal_places=2, default=0)
    widthcm= models.DecimalField(max_digits=6, decimal_places=2, default=0)
    image = models.ImageField(upload_to='product_images')
    formaat=models.CharField(max_length=1, default= 'X', choices=FORMAAT_CHOICES)
    oriëntatie = models.CharField(max_length=1, default= 'X', choices=ORIËNTATIE_CHOICES)
    techniek = models.CharField(max_length=1, default= 'X', choices=TECHNIEK_CHOICES)
    prijs =models.CharField(max_length=1, default= 'X', choices=PRIJS_CHOICES)  
    prijstype =models.CharField(max_length=1, default= 'X', choices=PRIJSTYPE_CHOICES) 
    stijl =models.CharField(max_length=1, default= 'X', choices=STIJL_CHOICES)
    thema =models.CharField(max_length=1, default= 'X', choices=THEME_CHOICES)
    kunstenaar = models.ForeignKey(Artist, null=False, related_name="artworks", on_delete=models.CASCADE)
    lijst =models.CharField(max_length=1, default= 'X', choices=LIJST_CHOICES)
    

    def __str__(self):
        return self.name
        
        
class ProductImages(models.Model):
    product = models.ForeignKey(Product, related_name="product_images", on_delete=models.CASCADE)
    image = models.ImageField()

products/forms.py
from django import forms
from .models import Product

class ProductSearchForm(forms.ModelForm):
    search=forms.CharField(required=False, label="Search")
    class Meta:
        model=Product
        fields=['search', 'formaat' ,'oriëntatie' ,'techniek' ,'prijs' ,'prijstype' ,'stijl', 'kunstenaar', 'thema']

class ProductSellerForm(forms.ModelForm):
    class Meta:
        model=Product
        fields=['name', 'description', 'price', 'rent', 'lengthcm', 'widthcm', 'image', 'formaat', 'oriëntatie', 'techniek', 'prijs', 'prijstype', 'stijl', 'thema', 'kunstenaar', 'lijst']
     
    
  
        

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, ProductImages
from .forms import ProductSearchForm, ProductSellerForm
from django.db.models import Q

# Create your views here.
def product_list(request):
    products = Product.objects.all()
    search_form = ProductSearchForm()
    return render(request, "products/product_list.html", {'products': products, 'search_form': search_form})


def filter_product_list(request):


    products = Product.objects.all()
    
    if 'search' in request.GET:
        search = request.GET['search']
        
        query_by_name = Q(name__contains=search)
        query_by_description = Q(description__contains=search)

        products = products.filter(query_by_name | query_by_description)

    
    if request.GET['formaat'] != 'X':
        products = products.filter(formaat=request.GET['formaat'])

    if request.GET['oriëntatie'] != 'X':
        products = products.filter(oriëntatie=request.GET['oriëntatie'])
    
    if request.GET['techniek'] != 'X':
        products = products.filter(techniek=request.GET['techniek'])
    
    if request.GET['prijs'] != 'X':
        products = products.filter(prijs=request.GET['prijs'])
        
    if request.GET['prijstype'] != 'X':
        products = products.filter(prijstype=request.GET['prijstype'])
    
    if request.GET['stijl'] != 'X':
        products = products.filter(stijl=request.GET['stijl'])
    
    if request.GET['kunstenaar']:
        products = products.filter(kunstenaar=request.GET['kunstenaar'])
        
    if request.GET['thema'] != 'X':
        products = products.filter(thema=request.GET['thema'])

    search_form = ProductSearchForm(request.GET)
    return render(request, "products/product_list.html", {'products': products, 'search_form': search_form})

    
def product_detail(request, id):
    product = get_object_or_404(Product, pk=id)
    product_images = ProductImages.objects.filter(product=id)
    return render(request, "products/product_detail.html", {'product': product, 'product_images':product_images})
    

def add_product(request):
    if request.method=="POST":
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('product_list')
        else:
            print(form.errors)
    else:
        form = ProductForm()
    
    return render(request, 'products/add_product.html', {'form':form})
        
        
def edit_product(request, id):
    product = get_object_or_404(Product, pk=id)
    
    if request.method=="POST":
        form = ProductSellerForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect(profile_seller)
    else:
        form = ProductSellerForm(instance=product)
    
    return render(request, "products/edit_product.html", {'product': product, 'form':form})

# def update_product(form):
#     # Update the DB with the differences
#     if form.is_valid():
#       product = form.save()
#         return redirect("profile_seller") 
#     else:
#           return render(request, "products/edit_product.html", {'product': product, 'form':form})

products/templates/products/add_product.html
{% extends "base.html" %} 
{% block content %}

<h1>Add Product</h1>


<form method="post" action="{% url 'add_product' %}">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit"/>
</form>


{% endblock content %}

products/templates/products/edit_product.html
{% extends "base.html" %} 
{% block content %}

<h1>Edit product</h1>


<form method="post" action="#">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Submit"/>
</form>


{% endblock content %}

products/templates/products/product_detail.html
{% extends "base.html" %} {% block content %}
<div class="container">
  <div class="row">
<div class= col-sm-12>
  <h3 class="card-title">{{product.name}}</h3>
  </div>
    <div class="col-sm-6">
      <div class="card mt-4">
        <img width="100%"  class="card-img-top img-fluid" src="{{MEDIA_URL}}{{product.image}}" alt="">
        <div class="card-body">
          <h3 class="card-title">{{product.name}}</h3>
          <h4>€{{product.price}}</h4>
          <p class="card-text">{{product.description}}</p>
          <span class="text-warning">
                {% for star in product.stars %}
                <i class="fa fa-star"></i>
                {% endfor %}
                {% if product.needs_half_star %}
                <i class="fa fa-star-half"></i>
                {% endif %}                
              </span>
        </div>
      </div>
    </div>
    <!-- /.card -->
    <div class="col-sm-6 ">
      <div>
        <div class=row>
        <div="left"><h4> Prijs Kunstwerk</h4></div>
        <div class="right"><h4> €{{product.price}}</h4></div>
        <h4> Betaalvorm {{product.get_prijstype_display}}</h4>
        <h4> Foormaat Kunstwerk {{product.get_formaat_display}}</h4>
        <h4> Orieëntatie Kunstwerk {{product.get_oriëntatie_display}}</h4>
        <h4> Gebruikte techniek {{product.get_techniek_display}}</h4>
        <h4> Stijl {{product.get_stijl_display}}</h4>
        <h4> Ingelijst {{product.get_lijst_display}}</h4>
        <h4> Horizontale lengte in cm {{product.get_lengthcm_display}}</h4>
        <h4> Verticale lengte in cm {{product.get_widthcm_display}}</h4>
      </div>

      <div>
        <form action="{% url 'view_checkout' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="id" value="{{product.id}}" />
          <p><input class="btn btn-success" type="submit" value="Koop nu" /></p>
        </form>

        <form action="{% url 'add_to_cart' %}" method="post">
          {% csrf_token %}
          <input type="hidden" name="id" value="{{product.id}}" />
          <input type="hidden" name="quantity" value="1"/>
          <p><input class="btn btn-success" type="submit" value="Neem dit kunstwerk in huis" /></p>
        </form>
      </div>

    </div>
    <!-- /.col-lg-9 -->


  </div>
  <div ='row'
  <div class="col-sm-3">
        {% for image in product_images %}
            <img width="70%" class="card-img-top img-fluid" src="{{MEDIA_URL}}{{image.image}}" alt=""><br>
        {% endfor %}
      </div>
    </div>
</div>
{% endblock content %}

products/templates/products/product_list.html
{% extends "base.html" %}
{% load static %}

    {% block head_style %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'css/product_list.css' %}">
    {% endblock head_style %}

{% block content %}
    <!--<section id="filters" class="column red relative">-->
    <!--    <div class= "container-fluid">-->
    <!--        <div class= "row">-->
    <!--            <div class="col-sm-12 searchbox">-->
            
    <!--<form method='get' action="{% url 'filter_product_list' %}" enctype="multipart/form-data">-->
    <!--     {{ search_form }}  -->
    <!--     <input type="submit" value="Search"/>-->
    <!--</form>-->
    <section class="container">
        <div class="row">
            <div class="col-sm-12 text-center">
                <h1>Collectie</h1>
            </div>
        </div>
    </section>
    
    <section id="filters" class="column red relative">
        <form method="get" action="{% url 'filter_product_list' %}" id="filter"  enctype="multipart/form-data">
            
                        
    <!--    <section class="container menu">-->
    <!--        <section class="row">-->
    <!--            <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
                    
    <!--                <section class="row">-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Stijl:</h3>-->
    <!--                        <select name="stijlen"><option value={{ search_form.stijl }}</select></section>-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Oriëntatie:</h3>-->
    <!--                        <select name="orientaties"><option value={{ search_form.oriëntatie }}</option></select></section>-->
    <!--                </section>-->
    <!--                <section class="row">-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Techniek:</h3>-->
    <!--                        <select name="tecjniek"><option value={{ search_form.techniek }}</option></select></section>-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Kunstenaar:</h3>-->
    <!--                        <select name="kunstenaar"><option value={{ search_form.kunstenaar }}</option></select></section>-->
    <!--                </section>-->
                    
    <!--            </section>-->
                
    <!--            <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
                    
    <!--               <section class="row">-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Thema:</h3>-->
    <!--                        <select name="Thema"><option value={{ search_form.thema }}</select></section>-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Formaat:</h3>-->
    <!--                        <select name="Formaat"><option value={{ search_form.formaat }}</option></select></section>-->
    <!--                </section>-->
    <!--                <section class="row">-->
                        <!--<section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
                        <!--    <h3>Zoek op:</h3>-->
                        <!--    <select name="kunstenaar"><option value={{ search_form.kunstenaar }}</option></select></section>-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3 class="nomargin">Zoek op:</h3>-->
    <!--                        <div class="filter-search">-->
    <!--                            <input type="text"  placeholder="Titel, nummer, etc..." class="{{ search_form.search }}"/>-->
    <!--                            <ul class="custom-autocomplete"></ul>-->
    <!--                            <img src="https://kunstuitleen.nl/wp-content/themes/kunstuitleen/images/thuis-filter-search.svg" alt="Zoeken >" class="filter-submit" />-->
    <!--                        </div>-->
    <!--                </section>-->
                    
    <!--            </section>-->
    <!--        </section>-->
    <!--                </section>-->
    <!--    </form>-->
    <!--</section>-->
    <nav
  style="height: 144px; "class="filter-navbar ">
                    <div class="categories-wrapper">
                        <div class="categories-container">
                            <ul class="categories container" data-filter="type">
                                <li class="active">
                                    <a href="#all">All</a>
                                </li>
                                <li>
                                    <a href="#big-bang">Big Bang</a>
                                </li>
                                <li>
                                    <a href="#poly">poly</a>
                                </li>
                                <li>
                                    <a href="#sacred-geometry">Sacred Geometry</a>
                                </li>
                            </ul>
                            <ul class="categories container" data-filter="tag">
                                <li class="active">
                                    <a href="#all">All</a>
                                </li>
                                <li>
                                    <a href="#circle">circle</a>
                                </li>
                                <li>
                                    <a href="#fillscreen">Fillscreen</a>
                                </li>
                                <li>
                                    <a href="#hexagon">Hexagon</a>
                                </li>
                            </ul>
                            <ul class="categories container" data-filter="variant">
                                <li>
                                    <select name="size">
                                        <option selected value="all">size</option>
                                        <option value="small">small</option>
                                        <option value="medium">medium</option>
                                        <option value="large">large</option>
                                    </select>
                                </li>
                                <li>
                                    <select name="color">
                                        <option selected value="all">color</option>
                                        <option value="red">red</option>
                                        <option value="white">white</option>
                                        <option value="blue">blue</option>
                                    </select>
                                </li>
                            </ul>
                        </div>
                    </div>
                </nav>
    
    <hr>
    
    <!--<section id="filters" class="column red relative">-->
    <!--    <form method="get" action="{% url 'filter_product_list' %}" id="filter"  enctype="multipart/form-data">-->
            
                        
    <!--    <section class="container">-->
    <!--        <section class="row">-->
    <!--            <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
                    
    <!--                <section class="row">-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3 class="nomargin">Zoek op:</h3>-->
    <!--                        <div class="filter-search">-->
    <!--                            <input type="text" name="c" id="c" value="" placeholder="Titel, nummer, etc..." />-->
    <!--                            <ul class="custom-autocomplete"></ul>-->
    <!--                            <img src="https://kunstuitleen.nl/wp-content/themes/kunstuitleen/images/thuis-filter-search.svg" alt="Zoeken >" class="filter-submit" />-->
    <!--                        </div>-->
    <!--                    </section>-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6 filter-kunstenaars">-->
    <!--                        <br class="clear hidden-sm hidden-md hidden-lg" />-->
    <!--                        <h3 class="nomargin">Kunstenaars:</h3>-->
    <!--                        <select name="kunstenaars">-->
    <!--                            <option value="">Alle kunstenaars</option>-->
    <!--                        </select>-->
    <!--                    </section>-->
    <!--                </section>-->
    <!--                <section class="row">-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Stijl:</h3>-->
    <!--                        <select name="stijlen"><option value="">Kies een stijl</option><option value="abstract">Abstract</option><option value="figuratief">Figuratief</option><option value="realistisch">Realistisch</option></select>                        </section>-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Oriëntatie:</h3>-->
    <!--                        <select name="orientaties"><option value="">Kies een orientatie</option><option value="liggend">Liggend</option><option value="staand">Staand</option><option value="vierkant">Vierkant</option></select>                        </section>-->
    <!--                </section>-->
                    
    <!--            </section>-->
                
    <!--            <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
                    
    <!--                <h3 class="nomargin">Maandbedrag:</h3>-->
    <!--                <select name="maandbedragen"><option value={{ search_form.prijs }}</select>                    -->
    <!--                <section class="row">-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Formaat:</h3>-->
    <!--                        <select name="formaten"><option value="">Kies een formaat</option><option value="groot">Groot</option><option value="klein">Klein</option><option value="middel">Middel</option></select>                        </section>-->
    <!--                    <section class="col-xs-12 col-sm-6 col-md-6 col-lg-6">-->
    <!--                        <h3>Techniek:</h3>-->
    <!--                        <select name="technieken"><option value="">Kies een techniek</option><option value="fotografie">Fotografie</option><option value="grafiek">Grafiek</option><option value="origineel">Origineel</option><option value="sculptuur">Sculptuur</option></select>                        </section>-->
    <!--                </section>-->
                    
    <!--            </section>-->
    <!--        </section>-->
    <!--                </section>-->
    <!--    </form>-->
    <!--</section>-->
    <!--<form action="" method="post">-->
    <!--    <div class="row">-->
    <!--        <div class="col-sm-3" id="formaat" class="">{{ search_form.search }}</div>-->
    <!--        <div class="col-sm-3" id="formaat" class="">{{ search_form.formaat }}</div>-->
    <!--        <div class="col-sm-3" id="oriëntatie" class="">{{ search_form.oriëntatie }}</div>-->
    <!--        <div class="col-sm-3" id="techniek" class="">{{ search_form.techniek }}</div>-->
    <!--    </div>-->
         
    <!--    <div class="row">-->
    <!--        <div class="col-sm-3 " id="formaat" class="">{{ search_form.prijs }}</div>-->
    <!--        <div class="col-sm-3" id="oriëntatie" class="">{{ search_form.stijl }}</div>-->
    <!--        <div class="col-sm-3" id="techniek" class="">{{ search_form.kunstenaar }}</div>-->
                <!--<div class="col-sm-3" id="techniek" class="">{{ search_form.thema }}</div>-->-->
    <!--    </div>-->
    <!--    <input type="submit" value="Submit">-->
    <!--</form>-->
    
    </div>
    </div>
    </div>
     </div>
        
  </section>      
    <div class="row">
    {% for product in products %}
                    <div class="col-sm-4 col-lg-4 col-md-4">
                        <div class="thumbnail">
                            <img src="{{MEDIA_URL}}{{product.image}}" alt="">
                            <div class="caption">
                                <h4 class="pull-right">€{{product.price}}</h4>
                                <h4><a href="{% url 'product_detail' product.id %}">{{product.name}}</a>
                                </h4>
                                <p>{{product.description | linebreaksbr }}</p>
                                <p>{{product.brand}}</p>
                            </div>
                            <div class="ratings">
                                <p class="pull-right">{{product.reviews_received.all|length}} reviews</p>
                                <p>
                                {% for star in product.stars %}
                                <i class="fa fa-star"></i>
                                {% endfor %}
                                {% if product.needs_half_star %}
                                <i class="fa fa-star-half"></i>
                                {% endif %}                

                                </p>
                            </div>
                        </div>
                    </div>
    {% if forloop.counter|divisibleby:3 %}
        </div><div class="row">
    {% endif %}
    {% endfor %}
    </div>
    </div>
<a class="backtotop" onclick="$('html, body').animate({ scrollTop: 0 });">Terug naar boven</a>
{% endblock content %}